// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CharacterImage: typeof import('./src/components/Character/CharacterImage.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    GridCharacterCard: typeof import('./src/components/Grid/Character/GridCharacterCard.vue')['default']
    GridCharacterList: typeof import('./src/components/Grid/Character/GridCharacterList.vue')['default']
    GridFilterSearch: typeof import('./src/components/Grid/Filter/GridFilterSearch.vue')['default']
    GridFilterStatus: typeof import('./src/components/Grid/Filter/GridFilterStatus.vue')['default']
    GridNavigation: typeof import('./src/components/Grid/GridNavigation.vue')['default']
    GridSkeletonCard: typeof import('./src/components/Grid/GridSkeletonCard.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Hero: typeof import('./src/components/Layout/Hero.vue')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCifFr: typeof import('~icons/cif/fr')['default']
    IconCifGb: typeof import('~icons/cif/gb')['default']
    IconMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiCircle: typeof import('~icons/mdi/circle')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
  }
}

export { }
